FROM node:22-bookworm-slim AS build
WORKDIR /app
ENV DATABASE_URL=file:/app/prisma/prod.db
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npx prisma db push --skip-generate && npx ts-node prisma/seed.ts && npm run build

FROM node:22-bookworm-slim
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/prisma ./prisma
COPY container-start.js ./
EXPOSE 80
CMD ["node", "container-start.js"]